### ISSUE TITLE
没有服务端代码吗?

### ISSUE THREAD

**Issue by xinle** [EchoBoy/chineseSearch#1]
有没有服务端的代码呀

**Comment by ligand-lg** [comment]
微信提供 **云开发** 功能，也就是一个简单的服务端。我这里只使用了它的数据库功能，提前把所有数据传上去，之后小程序直接查询数据库，也就没有后台。具体 **云开发** 看[官方文档](https://developers.weixin.qq.com/miniprogram/dev/wxcloud/basis/getting-started.html)
