### ISSUE TITLE
小程序报错。。

### ISSUE THREAD

**Issue by falali009** [EchoBoy/chineseSearch#2]
Uncaught (in promise) Error: errCode: -1  | errMsg: collection.get:fail operateWXData:fail invalid scope; at collection.get api;

**Comment by ligand-lg** [comment]
你是在自己本地运行？那就是数据库的错误，你数据库没有初始化，具体看[ 微信官方文档](https://developers.weixin.qq.com/miniprogram/dev/wxcloud/basis/getting-started.html)，数据库就是tools/graphics-618dbab.txt 一行一条 json。
